cmake_minimum_required(VERSION 3.12)
project(ezExplorerFileDropMenu LANGUAGES CXX)

add_library(ezExplorerFileDropMenu SHARED handler.cpp handler.def)
target_compile_features(ezExplorerFileDropMenu PRIVATE cxx_std_17)
target_compile_definitions(ezExplorerFileDropMenu PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN)
target_link_libraries(ezExplorerFileDropMenu PRIVATE ole32 shell32 advapi32)
set_target_properties(ezExplorerFileDropMenu PROPERTIES OUTPUT_NAME "ezExplorerFileDropMenu")
