cmake_minimum_required(VERSION 3.12)
project(SymbolicLinkExplorerContextMenu LANGUAGES CXX)

add_library(SymbolicLinkExplorerContextMenu SHARED handler.cpp handler.def)
target_compile_features(SymbolicLinkExplorerContextMenu PRIVATE cxx_std_17)
target_compile_definitions(SymbolicLinkExplorerContextMenu PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN)
target_link_libraries(SymbolicLinkExplorerContextMenu PRIVATE ole32 shell32 advapi32)
set_target_properties(SymbolicLinkExplorerContextMenu PROPERTIES OUTPUT_NAME "SymbolicLinkExplorerContextMenu")
