$ErrorActionPreference = "Stop"
$install = Join-Path $env:LOCALAPPDATA "SymbolicLinkExplorerContextMenu"
Write-Host "architecture: $([Environment]::Is64BitOperatingSystem)"
Write-Host "install: $install"
Write-Host "dll: $(Test-Path (Join-Path $install 'SymbolicLinkExplorerContextMenu.dll'))"
Write-Host "worker: $(Test-Path (Join-Path $install 'worker.exe'))"
reg.exe query "HKCU\Software\Classes\CLSID\{6d4d8ef0-3e69-4f5d-8d5a-1f8cb0f2b9c4}\InProcServer32"
reg.exe query "HKCU\Software\Classes\Directory\shellex\DragDropHandlers\SymbolicLinkExplorerContextMenu"
